version: "3"
services: 
    app:
        container_name: hello-world
        restart: always
        build: .
        ports: 
            - '30:8000'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27018:27017"